### ISSUE TITLE
File transfer from ESP32 to Android

### ISSUE THREAD

**Issue by MathieuDeprez** [PranjalKushwaha/ESP32-Bluetooth-FTP#7]
Hello,

Sending a file from an Android device to an ESP32 works very well, thank you very much for that.

Is it possible (or will it be possible) to send a file from the ESP32 to an Android device?

**Comment by PranjalKushwaha** [comment]
Thanks @MathieuDeprez ,
Currently, it is not possible. This will be added in the future.
